services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      # Mount the src directory from the host to /app/src in the container
      # This allows for live reloading of code changes.
      # Note: /app is the WORKDIR specified in the Dockerfile.
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    # Environment variables can be set here if needed, e.g.:
    # environment:
    #   - MY_VARIABLE=my_value
    # depends_on:
      # - db # If you had a database service, for example

# You can define other services here, like a database, frontend, etc.
# volumes:
#   postgres_data: # Example of a named volume for database persistence
